global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['mc-monitor:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
