FROM itzg/minecraft-server

ENV EULA="true"
ENV RCON_ENABLED="true"
ENV TYPE="VANILLA"
ENV VERSION="1.20.1"
ENV TZ="Asia/Tokyo"
ENV INIT_MEMORY="1G"
ENV MAX_MEMORY="4G"
ENV JVM_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
